#!/usr/bin/env bash
#Configure domain zone and subdomain


function print_domaininfo () {
   cmd=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $cmd" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ $# -eq 2 ]; then
	print_domaininfo "$1" "$2"

elif [ $# -eq 1 ]; then
	print_domaininfo "$1" "www"
	print_domaininfo "$1" "lb-01"
	print_domaininfo "$1" "web-01"
	print_domaininfo "$1" "web-02"
fi

