#!/usr/bin/env bash
#A Bash script that Install nginx web server to a server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
