#!/usr/bin/env bash
#Using your debugging skills, find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80

tosearch="8080 default_server"
replacement="80 default_server"

#search and replace using sed
sed -i "s/$tosearch/$replacement/"  /etc/nginx/sites-enabled/default

#restart nginx
service nginx restart
