#!/usr/bin/env bash
# This script is displaying "school" file status

file="school"

if [ -e "$file" ]; then
    
	echo "$file file exists"
	if [ -f "$file" ]; then
		if [ -s "$file" ]; then
			echo "$file file is not empty"
		else
			echo "$file file is empty"
		fi
		echo "$file is a regular file"
	else
		echo "$file file is not empty"
    fi


else
    echo "$file file does not exist"
fi
