#!/usr/bin/env bash
#a Bash script that run as nginx as nginx user && listen on all active IPs on port 8080 v2
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80 default_server/8080 default_server/"  /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx restart
